# Generated by Django 2.0.13 on 2019-04-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settysettings',
            name='name',
            field=models.CharField(max_length=190, primary_key=True, serialize=False),
        ),
    ]
