# Generated by Django 2.0.3 on 2020-01-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settysettings',
            name='app_name',
            field=models.CharField(
                blank=True,
                choices=[
                    ('django.contrib.admin', 'django.contrib.admin'),
                    ('django.contrib.auth', 'django.contrib.auth'),
                    ('django.contrib.contenttypes', 'django.contrib.contenttypes'),
                    ('django.contrib.sessions', 'django.contrib.sessions'),
                    ('django.contrib.messages', 'django.contrib.messages'),
                    ('django.contrib.staticfiles', 'django.contrib.staticfiles'),
                    ('setty.apps.DjangoSettyConfig', 'setty.apps.DjangoSettyConfig'),
                ],
                max_length=190,
            ),
        ),
    ]
